### ISSUE TITLE
Local install has JS and Laravel errors

### ISSUE THREAD

**Issue by xavez** [iRail/hyperRail#181] opened 2016-07-13 06:12 UTC
I get a bunch of errors when I try to run the `master` branch locally:

Setup didn’t give any errors. Composer, npm, bower, bundler . . . all did their thing (or so it seems)

![](http://c.xvr.io/0X1d333D0W3x/Image%202016-07-13%20at%208.09.31%20AM.png)
![](http://c.xvr.io/0p3h2Z331m1K/Image%202016-07-13%20at%208.11.09%20AM.png)

Any help appreciated :-)

**Comment by SerkanYildiz** [comment] 2016-07-13 07:47
Hi Xavez,

Do you have any logs / Php errors (right click + view source)?

**Comment by xavez** [comment] 2016-07-13 08:27
@SerkanYildiz you mean apart from the ones on the screenshots I posted in the initial issue?

**Comment by SerkanYildiz** [comment] 2016-07-13 08:29
Yes error logs of apache/php errors would be awesome

**Comment by xavez** [comment] 2016-07-13 09:26
No errors as far as I can see . . .

**Comment by pietercolpaert** [comment] 2016-07-13 10:09
That's indeed not supposed to happen... It looks like a problem with grunt though as the javascript isn't returning the right things. Will try to reproduce!

**Comment by pietercolpaert** [comment] 2016-07-13 11:26
I have been able to reproduce the problem. In the process, I also encountered this issue (which was fixed by the comment): https://github.com/gruntjs/grunt/issues/1488#issuecomment-223139509

Now I'm going to try to fix your problem and keep you posted ;)

**Comment by pietercolpaert** [comment] 2016-07-13 17:52
Seems like something that's not working due to weird grunt updates. Ugh. Why are we using grunt at all? :p

I'm trying to fix things in the feature-fixgrunt branch...

**Comment by pietercolpaert** [comment] 2016-07-13 19:20
@Tjoosten will now take a look at this and see whether he can change the grunt to gulp by tomorrow.

@SerkanYildiz Keep us posted if you find a fix!

@bramdevries As you put grunt in place before the laravel migration, maybe you can find a quicker fix?

**Comment by Tjoosten** [comment] 2016-07-13 19:20
Alright. @pietercolpaert pinged me about this one. I started working on this. Can someone give me the reproduction steps for this issue?

**Comment by pietercolpaert** [comment] 2016-07-13 19:20
@Tjoosten just try to install it and you'll encounter it. See README.md

**Comment by Tjoosten** [comment] 2016-07-13 19:21
alright?

**Comment by bramdevries** [comment] 2016-07-13 19:44
Fixed the angular issue in https://github.com/iRail/hyperRail/pull/182. Not sure about the bootstrap one (tooltip error)

**Comment by pietercolpaert** [comment] 2016-07-14 09:11
@xavez can you try again to install hyperrail? Thanks @bramdevries and @Tjoosten for your time and effort!

**Closed by pietercolpaert** 2016-07-14 09:11 UTC

**Comment by xavez** [comment] 2016-07-14 12:49
Works for me! 👏👏👏
